[package]
name        = "adaptor-extras"
description = "An incubator for Java interop functions for Flix"
version     = "0.2.1"
flix        = "0.75.3"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]
"github:stephentetley/effect-extras" = { version = "0.4.1", security = "unrestricted" }

[mvn-dependencies]
